### PR TITLE
Add router

### PR DESCRIPTION
**Pull request by CalebBassham**
All I did was add vue-router and convert the current `App.vue` to `Home.vue` to prepare for having multiple pages.

For now I just have it in the default mode so it has to have a `#` in the url but I think that we should change it later to run in history mode in production so that it doesn't look weird to people. To use history mode in production we would just have to make sure that the [web server is configured properly](https://router.vuejs.org/en/essentials/history-mode.html) for that.

### CODE REVIEW

**Comment by TotomInc** [comment]
Thanks for your contribution. Is it possible to point to develop instead of master?

Your changes looks nice, as for the web server with the history type, we will stay with the default mode since we can't edit config of the server. It's not a big deal IMO.

**Comment by CalebBassham** [comment]
Alright, I am fine with that, as you said it isn't a very big deal. Just didn't know were this would be deployed and the restrictions of that.

**Comment by TotomInc** [comment]
Yep thanks for pointing this, I'll write a small about the workflow. Master is the stable branch, which will hold stable releases. Develop is our current branch where we develop new features. Once we reached a milestone, we merge develop into master and create a new release. We usually create new features on separate branches that we merge on develop.

**Comment by CalebBassham** [comment]
:+1:

**Comment by TotomInc** [comment]
Can you please resolve the conflicts @DarkPaladinUHC?

**Review by TotomInc — CHANGES_REQUESTED** [review]
Fix conflicts please.

**Comment by CalebBassham** [comment]
Also this commit was in the download documentation that you just merged before this so there are no changes between this and development. Closing.

**Pull request closed without merging**
